### ISSUE TITLE
error when SangerAlignment

### ISSUE THREAD

**Issue by lixiaopi1985** [roblanf/sangeranalyseR#35] opened 2020-04-06 18:59 UTC
Hi,

I got this error at the end of the output when running

`ITS2_contigs <- SangerAlignment(parentDirectory = "./ITS2/ab1/",
                               suffixForwardRegExp = "^.*_ITSS2F_.*.ab1$",
                               suffixReverseRegExp = "^.*_ITS4R_.*.ab1$")
`

`Error in validObject(.Object) : 
  invalid class “SangerAlignment” object: 1: invalid object for slot "contigsConsensus" in class "SangerAlignment": got class "function", should be or extend class "DNAString"
invalid class “SangerAlignment” object: 2: invalid object for slot "contigsAlignment" in class "SangerAlignment": got class "NULL", should be or extend class "DNAStringSet"
invalid class “SangerAlignment” object: 3: invalid object for slot "contigsTree" in class "SangerAlignment": got class "NULL", should be or extend class "phylo"
In addition: Warning message:
In IdClusters(dist, type = "both", showPlot = FALSE, processors = processorsNum,  :
  Substituting 2.62 for non-finite values in myDistMatrix.`

Folder looks like this:
`├── 26668_A01_4_ITSS2F_A01_008.ab1
├── 26668_A02_83_ITSS2F_A02_008.ab1
├── 26668_A03_97_ITSS2F_A03_016.ab1
├── 26668_A04_75_ITS4R_A04_016.ab1
├── 26668_A05_95_ITS4R_A05_024.ab1
├── 26668_B01_42_ITSS2F_B01_007.ab1
├── 26668_B02_85_ITSS2F_B02_007.ab1
├── 26668_B03_99_ITSS2F_B03_015.ab1
├── 26668_B04_77_ITS4R_B04_015.ab1
`

Is it the matching problem?
Thanks

**Comment by roblanf** [comment] 2020-04-06 22:01
Hi @lixiaopi1985, 

If you could send me your input data off list (http://robertlanfear.com/contact) I'd be happy to take a look and get back to you. Whatever the issue is, the error message certainly isn't very helpful! Once we have your data, we can fix the issue and/or the error message. 

Rob

**Comment by roblanf** [comment] 2020-04-14 03:11
Closing this after this commit: https://github.com/roblanf/sangeranalyseR/commit/71e026304fa741374812f27595ee48a4674b4527

@HowardChao implemented an improved feature for inputting a 3 column csv file to describe read groupings. I updated the docs.

**Closed as completed by roblanf** 2020-04-14 03:11 UTC
