### ISSUE TITLE
launchApp(my_aligned_contigs) issue, please help 

### ISSUE THREAD

**Issue by Vladislav-Shevtsov** [roblanf/sangeranalyseR#70] opened 2021-05-20 16:43 UTC
I have the following text appear:

INFO [2021-05-20 22:40:24] Your input is 'SangerAlignment' S4 instance
INFO [2021-05-20 22:40:24] >>> outputDir : C:\Users\VLADIS~1\AppData\Local\Temp\RtmpcXjzLO

Listening on http://127.0.0.1:4026
Warning: Error in value[[3L]]: Couldn't normalize path in `addResourcePath`, with arguments: `prefix` = 'AdminLTE-2.0.6'; `directoryPath` = 'D:/biocbuild/bbs-3.13-bioc/R/library/shinydashboard/AdminLTE'
  [No stack trace available]

Looking forward for your answer, 
Best regards, Vladislav Shevtsov

**Comment by Vladislav-Shevtsov** [comment] 2021-05-20 16:44
When window appear I see following:

An error has occurred!
Couldn't normalize path in `addResourcePath`, with arguments: `prefix` = 'AdminLTE-2.0.6'; `directoryPath` = 'D:/biocbuild/bbs-3.13-bioc/R/library/shinydashboard/AdminLTE'

**Comment by Kuanhao-Chao** [comment] 2021-05-22 23:37
Duplicate of #60.

**Comment by Kuanhao-Chao** [comment] 2021-05-22 23:37
Duplicate of #60 
I'll close this issue and let's discuss in #60.

**Closed as completed** 2021-05-22 23:39 UTC
