### ISSUE TITLE
make.readset seem not work as expected

### ISSUE THREAD

**Issue by czliubio** [roblanf/sangeranalyseR#32] opened 2020-03-09 07:03 UTC
Hello,
sangeranalyseR is very useful for batch processing the sanger sequencing data. 
I test this tool with two pairs of ab1 files [testab.zip](https://github.com/roblanf/sangeranalyseR/files/4305019/testab.zip). sample 002A and sample 008A, which are amplified by 27F and 1100R primer pair. 
 "merge.reads" function can generate a more than 900 bp concensus sequence. however "make.readset" function did not work  as expected. It seems that it did not align the two sequence correctly by overlap part, and generate a very curious  consensus sequence just 500 bp with many ambiguous bases.
Reviewing the alignment file, I guess that the "reverseComplement" did not work in "make.readset" and maybe in "make.readsets" either. And I wonder if I make some mistakes？ 
I will appreciate if you can give me some advice.
Thanks!

Kevin, Lau.

**Comment by roblanf** [comment] 2020-03-10 04:50
Hi Kevin,

Thanks for the bug report. I'm going to ask @HowardChao to take a look at this. The current situation is that Howard has completely rebuilt the package from the ground up, with a lot of new features too. 

@HowardChao, can you have a look at @czliubio's dataset (kindly provided at the link above) in your new version, and see how it goes. Once it's working, let us know and maybe provide some basic instructions for how Kevin can run his analysis. 

Kevin - maybe you can be our first beta-tester for the new version...

Rob

**Comment by thokall** [comment] 2020-03-10 09:16
If you are looking for beta-tester for the new version. I would be more than happy to contribute.

**Comment by Kuanhao-Chao** [comment] 2020-03-11 06:43
Hi Kevin, 

Thanks for using sangeranalyseR. I have rebuilt this package so you need to download the newest version from **develop** branch:

## Installation
```
install.packages("devtools")
library(devtools)
install_github("roblanf/sangeranalyseR”, ref=‘develop’)
library(sangeranalyseR)
```
----

## Change filenames
In the new version of sangeranalyseR, there are three different classes which are **sangerRead**, **sangerContig** and **sangerAlignment**.  In sangeranalyseR, each ab1 file corresponds to a **sangerRead** instance, and each sample corresponds to a **sangerContig** instance. The ab1 files that belong to the same sample have to share the same name. 

In your case, you have sample 002A and sample 008A, and each sample has two ab1 files. 
First, you need to change your ab1 filenames (two sample names  are : **002A-16S** and **008A-16S**)

* The original filenames: 
  1. 002A-16S_27F.ab1
  2. 002A-16S_1100R.ab1
  3. 008A-16S_27F.ab1
  4. 008A-16S_1100R.ab1

* You should change to: 
  1. 002A-16S_1_F.ab1
  2. 002A-16S_2_R.ab1
  3. 008A-16S_1_F.ab1
  4. 008A-16S_2_R.ab1

---

## sangeranalyseR data analysis
You can do data analysis at three different levels. I have successfully executed the following code. Please try them to see whether it works for you. 

### **sangerRead** level: 
```
A_chloroticaFFN <- ‘/path/to/testab/008A-16S_1_F.ab1'
sangerReadF <- new("SangerRead",
                    readFeature           = "Forward Read",
                    readFileName          = A_chloroticaFFN,
                    geneticCode           = GENETIC_CODE)

# Generate sangerRead report
generateReportSR(sangerReadF)
```

### **sangerContig** level: 
```
parentDir <- ‘/path/to/testab'
contigName <- "008A-16S"
suffixForwardRegExp <- "_[0-9]*_F.ab1"
suffixReverseRegExp <- "_[0-9]*_R.ab1"
sangerContig <- new("SangerContig",
                     inputSource           = "ABIF",
                     parentDirectory       = parentDir,
                     contigName            = contigName,
                     suffixForwardRegExp   = suffixForwardRegExp,
                     suffixReverseRegExp   = suffixReverseRegExp)

# Launch sangerContig graphical Shiny app
launchAppSC(sangerContig)

# Generate sangerContig report
generateReportSC(sangerContig)
```

### **sangerAlignment** level: 
```
parentDir <-  ‘/path/to/testab'
suffixForwardRegExp <- "_[0-9]*_F.ab1"
suffixReverseRegExp <- "_[0-9]*_R.ab1"
sangerAlignment <- new("SangerAlignment",
                       inputSource           = "ABIF",
                       parentDirectory       = parentDir,
                       suffixForwardRegExp   = suffixForwardRegExp,
                       suffixReverseRegExp   = suffixReverseRegExp)

# Launch sangerAlignment graphical Shiny app
launchAppSA(sangerAlignment)

# Generate sangerAlignment report
generateReportSA(sangerAlignment)
```

This is the **sangerAlignment** data analysis report generated by sangeranalyseR: https://drive.google.com/open?id=1Mt7u92BcpmkVtbJGu7Ndf-euBVHJNJ8p

For more details about sangeranalyseR, please refer to the documentation: https://sangeranalyser.readthedocs.io/en/latest/. We are currently doing some minor changes and will release the beta version recently. If you have any problems, please let me know! Thank you!

Howard

**Comment by Kuanhao-Chao** [comment] 2020-03-11 06:50
Hi @thokall,

Thanks for willing to help! We are currently doing some minor changes and will release the beta version recently. Once we are done, we will let you know as soon as possible. Thank you!

Howard

**Comment by czliubio** [comment] 2020-03-12 02:20
> Hi Kevin,
> 
> Thanks for using sangeranalyseR. I have rebuilt this package so you need to download the newest version from **develop** branch:
> 
> ## Installation
> ```
> install.packages("devtools")
> library(devtools)
> install_github("roblanf/sangeranalyseR”, ref=‘develop’)
> library(sangeranalyseR)
> ```
> 
> ## Change filenames
> In the new version of sangeranalyseR, there are three different classes which are **sangerRead**, **sangerContig** and **sangerAlignment**. In sangeranalyseR, each ab1 file corresponds to a **sangerRead** instance, and each sample corresponds to a **sangerContig** instance. The ab1 files that belong to the same sample have to share the same name.
> 
> In your case, you have sample 002A and sample 008A, and each sample has two ab1 files.
> First, you need to change your ab1 filenames (two sample names are : **002A-16S** and **008A-16S**)
> 
> * The original filenames:
>   
>   1. 002A-16S_27F.ab1
>   2. 002A-16S_1100R.ab1
>   3. 008A-16S_27F.ab1
>   4. 008A-16S_1100R.ab1
> * You should change to:
>   
>   1. 002A-16S_1_F.ab1
>   2. 002A-16S_2_R.ab1
>   3. 008A-16S_1_F.ab1
>   4. 008A-16S_2_R.ab1
> 
> ## sangeranalyseR data analysis
> You can do data analysis at three different levels. I have successfully executed the following code. Please try them to see whether it works for you.
> 
> ### **sangerRead** level:
> ```
> A_chloroticaFFN <- ‘/path/to/testab/008A-16S_1_F.ab1'
> sangerReadF <- new("SangerRead",
>                     readFeature           = "Forward Read",
>                     readFileName          = A_chloroticaFFN,
>                     geneticCode           = GENETIC_CODE)
> 
> # Generate sangerRead report
> generateReportSR(sangerReadF)
> ```
> 
> ### **sangerContig** level:
> ```
> parentDir <- ‘/path/to/testab'
> contigName <- "008A-16S"
> suffixForwardRegExp <- "_[0-9]*_F.ab1"
> suffixReverseRegExp <- "_[0-9]*_R.ab1"
> sangerContig <- new("SangerContig",
>                      inputSource           = "ABIF",
>                      parentDirectory       = parentDir,
>                      contigName            = contigName,
>                      suffixForwardRegExp   = suffixForwardRegExp,
>                      suffixReverseRegExp   = suffixReverseRegExp)
> 
> # Launch sangerContig graphical Shiny app
> launchAppSC(sangerContig)
> 
> # Generate sangerContig report
> generateReportSC(sangerContig)
> ```
> 
> ### **sangerAlignment** level:
> ```
> parentDir <-  ‘/path/to/testab'
> suffixForwardRegExp <- "_[0-9]*_F.ab1"
> suffixReverseRegExp <- "_[0-9]*_R.ab1"
> sangerAlignment <- new("SangerAlignment",
>                        inputSource           = "ABIF",
>                        parentDirectory       = parentDir,
>                        suffixForwardRegExp   = suffixForwardRegExp,
>                        suffixReverseRegExp   = suffixReverseRegExp)
> 
> # Launch sangerAlignment graphical Shiny app
> launchAppSA(sangerAlignment)
> 
> # Generate sangerAlignment report
> generateReportSA(sangerAlignment)
> ```
> 
> This is the **sangerAlignment** data analysis report generated by sangeranalyseR: https://drive.google.com/open?id=1Mt7u92BcpmkVtbJGu7Ndf-euBVHJNJ8p
> 
> For more details about sangeranalyseR, please refer to the documentation: https://sangeranalyser.readthedocs.io/en/latest/. We are currently doing some minor changes and will release the beta version recently. If you have any problems, please let me know! Thank you!
> 
> Howard

Hi Howard,
Really appreciate for your great help. It works now. The new version is fantastic.
I work on the bacterial 16S sequencing, and generated large amount of 16S seqences from sanger sequencer. I was looking for better tools for quality control of these sequences, and make comparison with commercial tools (like KBcaller with ABI sequencer) and other open-source tools.  If real data test are needed, I would be ready to join.
Now I still have some questions:
1. It is possible to calculate the quality of consensus sequence (the contig), since the single reads quality is obtained. But I did not found the option.
2. It is possible to detect the indels in the sequence without the ref sequences. 16S sequences are not amino acid coding. Some times, we found there is half single peak and half multi peaks in a 
 trace file, which is possibly caused by the indels in the 16S copies. Can this be detected and resolve to separate sequences by this package?

I really appreciate your help, and I look look forward to your kind reply.

Sincerely,
Kevin

**Comment by roblanf** [comment] 2020-03-12 02:27
Hi Kevin,

"It is possible to calculate the quality of consensus sequence (the contig), since the single reads quality is obtained. But I did not found the option."

I guess so, yes. Do you know of any references or standard approaches for calculating consensus quality? We should be able to implement anything that exists.

"It is possible to detect the indels in the sequence without the ref sequences. 16S sequences are not amino acid coding. Some times, we found there is half single peak and half multi peaks in a
trace file, which is possibly caused by the indels in the 16S copies. Can this be detected and resolve to separate sequences by this package?"

In principle the answer to this is 'yes'. But again, we would probably need more details and some test files, as well as some idea of an existing algorithm that we can implement to do this. Neither of us do a lot of 16S sequencing (though we know what it is and generally understand what you're talking about, of course). Any help you can give us here, even just pointing us to a couple of references that do something like what you're talking about, would be very useful.

Cheers,

Rob

**Comment by czliubio** [comment] 2020-03-12 04:17
Hi Rob,

Following are some papers I read recently:
1. A standalone python script OverlapPER can merge reads into contig by overlap length and the minimum similarity, and then calculate the quality of consensus sequence . Reference paper here https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6083499/. And sangeranalyseR seems to merge reads not by the overlap length?
2. Poly peak parser explain what the trace look like when the when a heterozygous indel exist. (https://doi.org/10.1002/dvdy.24183). However, it still needs reference sequence to determine the INDEL. Paper “Decoding of Superimposed Traces Produced by Direct Sequencing of Heterozygous Indels”(10.1371/journal.pcbi.1000113) might described the closest solution. Besides BCV (https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0054835) and CASEU (“https://www.ncbi.nlm.nih.gov/pubmed/32114382”) trying to unmixing the poly peaks might be also  solutions to separate heterozygous copies and thus detect the indels by alignment. 
Hope these might help. If test ab1 files are needed, I can collect some in one or two days.

Thanks for your kind help.

Best wishes,
Kevin

**Comment by roblanf** [comment] 2020-03-18 04:21
> * The original filenames:
>   
>   1. 002A-16S_27F.ab1
>   2. 002A-16S_1100R.ab1
>   3. 008A-16S_27F.ab1
>   4. 008A-16S_1100R.ab1
> * You should change to:
>   
>   1. 002A-16S_1_F.ab1
>   2. 002A-16S_2_R.ab1
>   3. 008A-16S_1_F.ab1
>   4. 008A-16S_2_R.ab1

@HowardChao, I'm not sure this renaming is necessary. Can't we cover the original filenames with regex?

a general solution might be to do this (any number of integers after the underscore and before the 'F' or 'R':

```
suffixForwardRegExp <- "_[0-9]*F.ab1"
suffixReverseRegExp <- "_[0-9]*R.ab1"
```

and a specific solution that would work for this minimal example (I'm assuming these are primer names) would be:

```
suffixForwardRegExp <- "_27F.ab1"
suffixReverseRegExp <- "_1100R.ab1"
```

Am I missing something?

**Comment by roblanf** [comment] 2020-03-18 04:45
I forgot that @czliubio gave us the data. I tried out both regexps above and they work fine. 

One thing to note with giving new users help with the package is that I suspect regexp will be by far the most challenging thing. As we start to see what folks struggle with, we should add sections to the help docs. E.g. once we have a few regexp examples from a variety of users, we could add a whole help section on defining regexps, with good examples that people can build on.

Anyway, I'm closing this issue for now because I think it's done. I shifted the other two suggestions for new features to new issues, so we can keep track.

**Closed as completed by roblanf** 2020-03-18 04:45 UTC

**Comment by Kuanhao-Chao** [comment] 2020-03-18 06:10
> > * The original filenames:
> >   
> >   1. 002A-16S_27F.ab1
> >   2. 002A-16S_1100R.ab1
> >   3. 008A-16S_27F.ab1
> >   4. 008A-16S_1100R.ab1
> > * You should change to:
> >   
> >   1. 002A-16S_1_F.ab1
> >   2. 002A-16S_2_R.ab1
> >   3. 008A-16S_1_F.ab1
> >   4. 008A-16S_2_R.ab1
> 
> @HowardChao, I'm not sure this renaming is necessary. Can't we cover the original filenames with regex?
> 
> a general solution might be to do this (any number of integers after the underscore and before the 'F' or 'R':
> 
> ```
> suffixForwardRegExp <- "_[0-9]*F.ab1"
> suffixReverseRegExp <- "_[0-9]*R.ab1"
> ```
> 
> and a specific solution that would work for this minimal example (I'm assuming these are primer names) would be:
> 
> ```
> suffixForwardRegExp <- "_27F.ab1"
> suffixReverseRegExp <- "_1100R.ab1"
> ```
> 
> Am I missing something?

Yes! Both regular expression methods work! There are only two reads in each contig in this example, so the second regular expression method works. But if there are **more reads in one contig**, then users should include the index in ab1 filename.

```
suffixForwardRegExp <- "_[0-9]*_27F.ab1"
suffixReverseRegExp <- "_[0-9]*_1100R.ab1"
```

1. 002A-16S_1_27F.ab1
2. 002A-16S_2_1100R.ab1
3. 008A-16S_1_27F.ab1
4. 008A-16S_2_1100R.ab1
